variables:
  Agent.Source.Git.ShallowFetchDepth: 120

trigger:
  branches:
    include:
    - azure-pipeline

pr:
- master
- azure-pipelines

jobs:
- job: build
  pool:
    vmImage: vs2015-win2012r2
  timeoutInMinutes: 360
  strategy:
    maxParallel: 4
    matrix:
#      x86:
#         OSGEO4W_ROOT: C:\OSGeo4W
#         OSGEO4W_ARCH: x86
#         CLCACHE_DIR: c:\clcache-x86
#         PLATFORM: x86
#         CC: C:\OSGeo4W\bin\clcache.bat
#         CXX: C:\OSGeo4W\bin\clcache.bat

      x86_64:
         OSGEO4W_ROOT: C:\OSGeo4W64
         OSGEO4W_ARCH: x86_64
#         CLCACHE_DIR: c:\clcache-x86_64
         PLATFORM: x64
#         CC: C:\OSGeo4W64\bin\clcache.bat
#         CXX: C:\OSGeo4W64\bin\clcache.bat

  steps:
  - checkout: self
    submodules: true
    persistCredentials: true

  - bash: |
      if [ "$BUILD_REASON" = "PullRequest" ]; then
        branch=$SYSTEM_PULLREQUEST_TARGETBRANCH
        pr=$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
      else
        branch=$BUILD_SOURCEBRANCHNAME
      fi

      echo "BRANCH: ${branch}"
      echo "PR: ${pr}"

      OSGEO4W_PKG=qfield-dev
      
      sha="${BUILD_SOURCEVERSION:0:10}"

      if [ "$BUILD_REASON" = "PullRequest" ]; then
        buildname="PR $pr / $branch ($BUILD_BUILDID) ($sha) ($OSGEO4W_PKG $target $OSGEO4W_ARCH)"   # no colons allowed here
      else
        buildname="$OSGEO4W_PKG-$version-$sha-$target-VC14-$OSGEO4W_ARCH"
      fi

      url=$buildname
      url=${url//(/%28}
      url=${url//)/%29}
      url=${url// /+}
      url="https://cdash.orfeo-toolbox.org/index.php?project=QGIS&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=$url&field2=site&compare2=61&value2=azure-pipelines"

      version="1.3.0" # TODO: make dynamic
      binary=1 # TODO: make dynamic

      echo "##vso[task.setvariable variable=TARGET]$target"
      echo "##vso[task.setvariable variable=OSGEO4W_PKG]$OSGEO4W_PKG"
      echo "##vso[task.setvariable variable=MAJOR]$major"
      echo "##vso[task.setvariable variable=MINOR]$minor"
      echo "##vso[task.setvariable variable=PATCH]$patch"
      echo "##vso[task.setvariable variable=BINARY]$binary"
      echo "##vso[task.setvariable variable=VERSION]$version"
      echo "##vso[task.setvariable variable=BUILDNAME]$buildname"
      echo "##vso[task.setvariable variable=DASHURL]$url"

    displayName: 'Setup build variables'

  - script: curl --output c:\setup-x86.exe https://cygwin.com/setup-x86.exe
    displayName: 'Download cygwin Installer'

  - script: curl --output c:\osgeo4w-setup.exe https://download.osgeo.org/osgeo4w/osgeo4w-setup-%OSGEO4W_ARCH%.exe
    displayName: 'Download OSGeo4W Installer'

  - script: curl --location-trusted --output c:\cmake.msi https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-win64-x64.msi
    displayName: 'Download CMake Installer'

  - script: curl --location-trusted --output c:\ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip
    displayName: 'Download Ninja'

  - powershell: ms-windows/osgeo4w/runasadmin.ps1 c:\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/temp/cygwin -P "bison,flex,git,poppler,doxygen,unzip"
    displayName: 'Install cygwin'

  - powershell: ms-windows/osgeo4w/runasadmin.ps1 c:\osgeo4w-setup.exe --autoaccept --advanced --arch $env:OSGEO4W_ARCH --quiet-mode --upgrade-also --root $env:OSGEO4W_ROOT --only-site -s http://download.osgeo.org/osgeo4w -l c:\temp\osgeo4w -P qgis-dev-deps -P python3-clcache
    displayName: 'Install OSGeo4W qgis-dev builddeps'

  - powershell: ms-windows/osgeo4w/runasadmin.ps1 c:\osgeo4w-setup.exe --autoaccept --advanced --arch $env:OSGEO4W_ARCH --quiet-mode --upgrade-also --root $env:OSGEO4W_ROOT --only-site -s http://download.osgeo.org/osgeo4w -l c:\temp\osgeo4w -P qgis-dev
    displayName: 'Install OSGeo4W qgis-dev'

  - script: |
      rmdir /s /q c:\temp\cygwin
      rmdir /s /q c:\temp\osgeo4w
    displayName: 'Clear package caches'

  - powershell: ms-windows/osgeo4w/runasadmin.ps1 msiexec.exe /X C:\Windows\Installer\146218.msi /qn /norestart /l*v c:\cmake-uninstall.log
    displayName: 'Uninstall old CMake'

  - powershell: ms-windows/osgeo4w/runasadmin.ps1 msiexec.exe /I c:\cmake.msi /qn /norestart /l*v c:\cmake-install.log
    displayName: 'Install CMake'

  - script: c:\cygwin\bin\unzip -o c:\ninja.zip -d %OSGEO4W_ROOT%\bin
    displayName: 'Extracting Ninja'

  - script: |
      PATH %OSGEO4W_ROOT%\bin;%ProgramFiles%\CMake\bin;%PATH%
      cmake --version
      ctest --version
      ninja --version
    displayName: 'Display tool versions'

  - script: |
      echo on
      PATH c:\cygwin\bin;%OSGEO4W_ROOT%\bin;%PATH%
      cd ms-windows\osgeo4w
      touch skippackage
      set OSGEO4W_CXXFLAGS=/MD /MP /Od /D NDEBUG
      package.cmd %VERSION% %BINARY% %OSGEO4W_PKG% %OSGEO4W_ARCH% %BUILD_SOURCEVERSION:~0,10% azure-pipelines
    displayName: 'Build QField'

  - task: Cache@2
    inputs:
      key: 'osgeo42 | "$(Agent.OS)"'
      path: $(OSGEO4W_ROOT)
    displayName: Cache OSGeo4W

# vim: set nowrap :

